[project]
name = "mcp-server-demo"
version = "0.1.0"
description = "Sample MCP server PoC for testing (BITS mockup)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.7.1",
]
